# Generated by Django 2.2.3 on 2019-07-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('consumer_key', models.CharField(max_length=200)),
                ('consumer_secret_key', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=200)),
                ('access_secret_token', models.CharField(max_length=200)),
            ],
        ),
    ]
