# Generated by Django 2.2.3 on 2019-07-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_auto_20190724_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='DmUserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('user_name', models.CharField(max_length=20)),
            ],
        ),
    ]
