# Generated by Django 2.2.3 on 2019-09-18 10:27

from django.db import migrations, models
import tweet.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=tweet.models.upload_location),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
