# Generated by Django 2.2.3 on 2019-09-19 10:21

from django.db import migrations, models
import django.utils.timezone
import tweet.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_auto_20190918_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(null=True)),
                ('tweet', models.TextField(blank=True, max_length=200, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=tweet.models.upload_location)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('schedule', models.DateTimeField(auto_now=True)),
                ('is_posted', models.BooleanField(default=False)),
            ],
        ),
    ]
