# Generated by Django 2.2.3 on 2019-09-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_scheduledtweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtweet',
            name='schedule',
        ),
        migrations.AddField(
            model_name='scheduledtweet',
            name='schedule_post',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='schedule_post',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
