# Generated by Django 2.2.3 on 2019-09-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0008_auto_20190919_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='is_posted',
            field=models.BooleanField(default=True),
        ),
    ]
