# Generated by Django 2.2.3 on 2019-09-19 13:11

from django.db import migrations, models
import tweet.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0009_auto_20190919_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtweet',
            name='document',
            field=models.FileField(blank=True, default=None, null=True, upload_to=tweet.models.upload_location),
        ),
        migrations.AlterField(
            model_name='scheduledtweet',
            name='tweet',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='document',
            field=models.FileField(blank=True, default=None, null=True, upload_to=tweet.models.upload_location),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
